version: '3.8'

services:
  dolos:
    build:
      context: .
      dockerfile: Dockerfile.dolos
    container_name: tx3-dolos
    ports:
      - "8164:8164"
    volumes:
      - ./devnet:/app/devnet
    networks:
      - tx3-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: tx3-nextjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    depends_on:
      - dolos
    networks:
      - tx3-network
    restart: unless-stopped

networks:
  tx3-network:
    driver: bridge

volumes:
  node_modules:
  next_cache:
